package com.iscactus.archaicraft.setup;

import com.iscactus.archaicraft.block.*;
import com.iscactus.archaicraft.block.kiln.KilnBlock;
import com.iscactus.archaicraft.block.mortar.MortarBlock;
import net.minecraft.block.*;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraft.block.trees.OakTree;
import net.minecraft.entity.EntityType;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.potion.Effects;
import net.minecraft.state.properties.BlockStateProperties;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.IBlockReader;
import net.minecraftforge.common.ToolType;
import net.minecraftforge.fml.RegistryObject;

import java.util.function.Supplier;
import java.util.function.ToIntFunction;

public class ModBlocks {
    // Aspen Tree
    public static final RegistryObject<Block> ASPEN_PLANKS = register("aspen_planks", () -> new Block(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.TERRACOTTA_BLACK).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_ASPEN_LOG = register("stripped_aspen_log", () -> new RotatedPillarBlock(AbstractBlock .Properties.of(Material.WOOD, ASPEN_PLANKS.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_ASPEN_WOOD = register("stripped_aspen_wood", () -> new RotatedPillarBlock(AbstractBlock.Properties.of(Material.WOOD, ASPEN_PLANKS.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASPEN_LOG = register("aspen_log", () -> new ModLogBlock(STRIPPED_ASPEN_LOG.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, MaterialColor.SNOW).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASPEN_WOOD = register("aspen_wood", () -> new ModLogBlock(STRIPPED_ASPEN_WOOD.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, ASPEN_LOG.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASPEN_STAIRS = register("aspen_stairs", () -> new StairsBlock(() -> ASPEN_PLANKS.get().defaultBlockState(), AbstractBlock.Properties.copy(ASPEN_PLANKS.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASPEN_SLAB = register("aspen_slab", () -> new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, ASPEN_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASPEN_FENCE = register("aspen_fence", () -> new FenceBlock(AbstractBlock.Properties.of(Material.WOOD, ASPEN_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASPEN_FENCE_GATE = register("aspen_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.of(Material.WOOD, ASPEN_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASPEN_DOOR = register("aspen_door", () -> new DoorBlock(AbstractBlock.Properties.of(Material.WOOD, ASPEN_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASPEN_TRAPDOOR = register("aspen_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.of(Material.WOOD, ASPEN_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion().isValidSpawn(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASPEN_PRESSURE_PLATE = register("aspen_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.of(Material.WOOD, ASPEN_PLANKS.get().defaultMaterialColor()).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASPEN_BUTTON = register("aspen_button", () -> new WoodButtonBlock(AbstractBlock.Properties.of(Material.DECORATION).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASPEN_LEAVES = register("aspen_leaves", () -> new LeavesBlock(AbstractBlock.Properties.of(Material.LEAVES, MaterialColor.COLOR_YELLOW).strength(0.2F).randomTicks().sound(SoundType.GRASS).noOcclusion().isValidSpawn(ModBlocks::ocelotOrParrot).isSuffocating(ModBlocks::never).isViewBlocking(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASPEN_SAPLING = register("aspen_sapling", () -> new SaplingBlock(new OakTree(),SaplingBlock.Properties.of(Material.PLANT, MaterialColor.COLOR_YELLOW).noCollission().randomTicks().instabreak().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASPEN_SIGN = registerNoItem("aspen_sign", () -> new StandingSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD), ModWoodType.ASPEN));
    public static final RegistryObject<Block> ASPEN_WALL_SIGN = registerNoItem("aspen_wall_sign", () -> new WallSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(ASPEN_SIGN.get()), ModWoodType.ASPEN));
    public static final RegistryObject<Block> POTTED_ASPEN_SAPLING = registerNoItem("potted_aspen_sapling", () -> new FlowerPotBlock(ASPEN_SAPLING.get(), AbstractBlock.Properties.of(Material.DECORATION).instabreak().noOcclusion()));

    public static final RegistryObject<Block> BEECH_PLANKS = register("beech_planks", () -> new Block(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.WOOD).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_BEECH_LOG = register("stripped_beech_log", () -> new RotatedPillarBlock(AbstractBlock .Properties.of(Material.WOOD, BEECH_PLANKS.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_BEECH_WOOD = register("stripped_beech_wood", () -> new RotatedPillarBlock(AbstractBlock.Properties.of(Material.WOOD, BEECH_PLANKS.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> BEECH_LOG = register("beech_log", () -> new ModLogBlock(STRIPPED_BEECH_LOG.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, MaterialColor.TERRACOTTA_BROWN).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> BEECH_WOOD = register("beech_wood", () -> new ModLogBlock(STRIPPED_BEECH_WOOD.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, BEECH_LOG.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> BEECH_STAIRS = register("beech_stairs", () -> new StairsBlock(() -> BEECH_PLANKS.get().defaultBlockState(), AbstractBlock.Properties.copy(BEECH_PLANKS.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> BEECH_SLAB = register("beech_slab", () -> new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, BEECH_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> BEECH_FENCE = register("beech_fence", () -> new FenceBlock(AbstractBlock.Properties.of(Material.WOOD, BEECH_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> BEECH_FENCE_GATE = register("beech_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.of(Material.WOOD, BEECH_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> BEECH_DOOR = register("beech_door", () -> new DoorBlock(AbstractBlock.Properties.of(Material.WOOD, BEECH_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> BEECH_TRAPDOOR = register("beech_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.of(Material.WOOD, BEECH_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion().isValidSpawn(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> BEECH_PRESSURE_PLATE = register("beech_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.of(Material.WOOD, BEECH_PLANKS.get().defaultMaterialColor()).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> BEECH_BUTTON = register("beech_button", () -> new WoodButtonBlock(AbstractBlock.Properties.of(Material.DECORATION).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> BEECH_LEAVES = register("beech_leaves", () -> new LeavesBlock(AbstractBlock.Properties.of(Material.LEAVES, MaterialColor.COLOR_LIGHT_GREEN).strength(0.2F).randomTicks().sound(SoundType.GRASS).noOcclusion().isValidSpawn(ModBlocks::ocelotOrParrot).isSuffocating(ModBlocks::never).isViewBlocking(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> BEECH_SAPLING = register("beech_sapling", () -> new SaplingBlock(new OakTree(),SaplingBlock.Properties.of(Material.PLANT).noCollission().randomTicks().instabreak().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> BEECH_SIGN = registerNoItem("beech_sign", () -> new StandingSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD), ModWoodType.BEECH));
    public static final RegistryObject<Block> BEECH_WALL_SIGN = registerNoItem("beech_wall_sign", () -> new WallSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(BEECH_SIGN.get()), ModWoodType.BEECH));
    public static final RegistryObject<Block> POTTED_BEECH_SAPLING = registerNoItem("potted_beech_sapling", () -> new FlowerPotBlock(BEECH_SAPLING.get(), AbstractBlock.Properties.of(Material.DECORATION).instabreak().noOcclusion()));

    public static final RegistryObject<Block> CITRON_PLANKS = register("citron_planks", () -> new Block(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.SAND).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_CITRON_LOG = register("stripped_citron_log", () -> new RotatedPillarBlock(AbstractBlock .Properties.of(Material.WOOD, CITRON_PLANKS.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_CITRON_WOOD = register("stripped_citron_wood", () -> new RotatedPillarBlock(AbstractBlock.Properties.of(Material.WOOD, CITRON_PLANKS.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CITRON_LOG = register("citron_log", () -> new ModLogBlock(STRIPPED_CITRON_LOG.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_GRAY).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CITRON_WOOD = register("citron_wood", () -> new ModLogBlock(STRIPPED_CITRON_WOOD.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, CITRON_LOG.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CITRON_STAIRS = register("citron_stairs", () -> new StairsBlock(() -> CITRON_PLANKS.get().defaultBlockState(), AbstractBlock.Properties.copy(CITRON_PLANKS.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CITRON_SLAB = register("citron_slab", () -> new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, CITRON_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CITRON_FENCE = register("citron_fence", () -> new FenceBlock(AbstractBlock.Properties.of(Material.WOOD, CITRON_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CITRON_FENCE_GATE = register("citron_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.of(Material.WOOD, CITRON_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CITRON_DOOR = register("citron_door", () -> new DoorBlock(AbstractBlock.Properties.of(Material.WOOD, CITRON_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CITRON_TRAPDOOR = register("citron_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.of(Material.WOOD, CITRON_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion().isValidSpawn(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CITRON_PRESSURE_PLATE = register("citron_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.of(Material.WOOD, CITRON_PLANKS.get().defaultMaterialColor()).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CITRON_BUTTON = register("citron_button", () -> new WoodButtonBlock(AbstractBlock.Properties.of(Material.DECORATION).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CITRON_LEAVES = register("citron_leaves", () -> new LeavesBlock(AbstractBlock.Properties.of(Material.LEAVES, MaterialColor.COLOR_LIGHT_GREEN).strength(0.2F).randomTicks().sound(SoundType.GRASS).noOcclusion().isValidSpawn(ModBlocks::ocelotOrParrot).isSuffocating(ModBlocks::never).isViewBlocking(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CITRON_SAPLING = register("citron_sapling", () -> new SaplingBlock(new OakTree(),SaplingBlock.Properties.of(Material.PLANT, MaterialColor.COLOR_LIGHT_GREEN).noCollission().randomTicks().instabreak().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CITRON_SIGN = registerNoItem("citron_sign", () -> new StandingSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD), ModWoodType.CITRON));
    public static final RegistryObject<Block> CITRON_WALL_SIGN = registerNoItem("citron_wall_sign", () -> new WallSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(CITRON_SIGN.get()), ModWoodType.CITRON));
    public static final RegistryObject<Block> POTTED_CITRON_SAPLING = registerNoItem("potted_citron_sapling", () -> new FlowerPotBlock(CITRON_SAPLING.get(), AbstractBlock.Properties.of(Material.DECORATION).instabreak().noOcclusion()));

    public static final RegistryObject<Block> EUCALYPTUS_PLANKS = register("eucalyptus_planks", () -> new Block(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.DIRT).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_EUCALYPTUS_LOG = register("stripped_eucalyptus_log", () -> new RotatedPillarBlock(AbstractBlock .Properties.of(Material.WOOD, EUCALYPTUS_PLANKS.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_EUCALYPTUS_WOOD = register("stripped_eucalyptus_wood", () -> new RotatedPillarBlock(AbstractBlock.Properties.of(Material.WOOD, EUCALYPTUS_PLANKS.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> EUCALYPTUS_LOG = register("eucalyptus_log", () -> new ModLogBlock(STRIPPED_EUCALYPTUS_LOG.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_LIGHT_GRAY).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> EUCALYPTUS_WOOD = register("eucalyptus_wood", () -> new ModLogBlock(STRIPPED_EUCALYPTUS_WOOD.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, EUCALYPTUS_LOG.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> EUCALYPTUS_STAIRS = register("eucalyptus_stairs", () -> new StairsBlock(() -> EUCALYPTUS_PLANKS.get().defaultBlockState(), AbstractBlock.Properties.copy(EUCALYPTUS_PLANKS.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> EUCALYPTUS_SLAB = register("eucalyptus_slab", () -> new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, EUCALYPTUS_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> EUCALYPTUS_FENCE = register("eucalyptus_fence", () -> new FenceBlock(AbstractBlock.Properties.of(Material.WOOD, EUCALYPTUS_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> EUCALYPTUS_FENCE_GATE = register("eucalyptus_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.of(Material.WOOD, EUCALYPTUS_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> EUCALYPTUS_DOOR = register("eucalyptus_door", () -> new DoorBlock(AbstractBlock.Properties.of(Material.WOOD, EUCALYPTUS_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> EUCALYPTUS_TRAPDOOR = register("eucalyptus_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.of(Material.WOOD, EUCALYPTUS_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion().isValidSpawn(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> EUCALYPTUS_PRESSURE_PLATE = register("eucalyptus_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.of(Material.WOOD, EUCALYPTUS_PLANKS.get().defaultMaterialColor()).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> EUCALYPTUS_BUTTON = register("eucalyptus_button", () -> new WoodButtonBlock(AbstractBlock.Properties.of(Material.DECORATION).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> EUCALYPTUS_LEAVES = register("eucalyptus_leaves", () -> new LeavesBlock(AbstractBlock.Properties.of(Material.LEAVES, MaterialColor.COLOR_CYAN).strength(0.2F).randomTicks().sound(SoundType.GRASS).noOcclusion().isValidSpawn(ModBlocks::ocelotOrParrot).isSuffocating(ModBlocks::never).isViewBlocking(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> EUCALYPTUS_SAPLING = register("eucalyptus_sapling", () -> new SaplingBlock(new OakTree(),SaplingBlock.Properties.of(Material.PLANT, MaterialColor.COLOR_CYAN).noCollission().randomTicks().instabreak().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> EUCALYPTUS_SIGN = registerNoItem("eucalyptus_sign", () -> new StandingSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD), ModWoodType.EUCALYPTUS));
    public static final RegistryObject<Block> EUCALYPTUS_WALL_SIGN = registerNoItem("eucalyptus_wall_sign", () -> new WallSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(EUCALYPTUS_SIGN.get()), ModWoodType.EUCALYPTUS));
    public static final RegistryObject<Block> POTTED_EUCALYPTUS_SAPLING = registerNoItem("potted_eucalyptus_sapling", () -> new FlowerPotBlock(EUCALYPTUS_SAPLING.get(), AbstractBlock.Properties.of(Material.DECORATION).instabreak().noOcclusion()));

    public static final RegistryObject<Block> MANGROVE_AERIAL_ROOTS = register("mangrove_aerial_roots", () -> new MangroveAerialRootsBlock(AbstractBlock.Properties.of(Material.WATER_PLANT, MaterialColor.COLOR_GRAY).noCollission().instabreak().sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_PLANKS = register("mangrove_planks", () -> new Block(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.SNOW).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_MANGROVE_LOG = register("stripped_mangrove_log", () -> new RotatedPillarBlock(AbstractBlock .Properties.of(Material.WOOD, MANGROVE_PLANKS.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_MANGROVE_WOOD = register("stripped_mangrove_wood", () -> new RotatedPillarBlock(AbstractBlock.Properties.of(Material.WOOD, MANGROVE_PLANKS.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_LOG = register("mangrove_log", () -> new ModLogBlock(STRIPPED_MANGROVE_LOG.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, MaterialColor.SNOW).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_WOOD = register("mangrove_wood", () -> new ModLogBlock(STRIPPED_MANGROVE_WOOD.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, MANGROVE_LOG.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_STAIRS = register("mangrove_stairs", () -> new StairsBlock(() -> MANGROVE_PLANKS.get().defaultBlockState(), AbstractBlock.Properties.copy(MANGROVE_PLANKS.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_STEM = register("mangrove_stem", () -> new MangroveStemTopBlock(AbstractBlock.Properties.of(Material.PLANT, MaterialColor.TERRACOTTA_WHITE).randomTicks().noCollission().instabreak().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_STEM_PLANT = registerNoItem("mangrove_stem_plant", () ->  new MangroveStemBlock(AbstractBlock.Properties.of(Material.PLANT, MaterialColor.TERRACOTTA_WHITE).noCollission().instabreak().sound(SoundType.WOOD)));
    public static final RegistryObject<Block> MANGROVE_SLAB = register("mangrove_slab", () -> new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, MANGROVE_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_FENCE = register("mangrove_fence", () -> new FenceBlock(AbstractBlock.Properties.of(Material.WOOD, MANGROVE_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_FENCE_GATE = register("mangrove_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.of(Material.WOOD, MANGROVE_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_DOOR = register("mangrove_door", () -> new DoorBlock(AbstractBlock.Properties.of(Material.WOOD, MANGROVE_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_TRAPDOOR = register("mangrove_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.of(Material.WOOD, MANGROVE_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion().isValidSpawn(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_PRESSURE_PLATE = register("mangrove_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.of(Material.WOOD, MANGROVE_PLANKS.get().defaultMaterialColor()).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_BUTTON = register("mangrove_button", () -> new WoodButtonBlock(AbstractBlock.Properties.of(Material.DECORATION).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_LEAVES = register("mangrove_leaves", () -> new LeavesBlock(AbstractBlock.Properties.of(Material.LEAVES, MaterialColor.COLOR_RED).strength(0.2F).randomTicks().sound(SoundType.GRASS).noOcclusion().isValidSpawn(ModBlocks::ocelotOrParrot).isSuffocating(ModBlocks::never).isViewBlocking(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_SAPLING = register("mangrove_sapling", () -> new SaplingBlock(new OakTree(),SaplingBlock.Properties.of(Material.PLANT).noCollission().randomTicks().instabreak().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MANGROVE_SIGN = registerNoItem("mangrove_sign", () -> new StandingSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD), ModWoodType.MANGROVE));
    public static final RegistryObject<Block> MANGROVE_WALL_SIGN = registerNoItem("mangrove_wall_sign", () -> new WallSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(MANGROVE_SIGN.get()), ModWoodType.MANGROVE));
    public static final RegistryObject<Block> MANGROVE_ROOTS = register("mangrove_roots", () -> new Block(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.WOOD).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> POTTED_MANGROVE_SAPLING = registerNoItem("potted_mangrove_sapling", () -> new FlowerPotBlock(MANGROVE_SAPLING.get(), AbstractBlock.Properties.of(Material.DECORATION).instabreak().noOcclusion()));
    public static final RegistryObject<Block> POTTED_MANGROVE_AERIAL_ROOTS = registerNoItem("potted_mangrove_aerial_roots", () -> new FlowerPotBlock(MANGROVE_AERIAL_ROOTS.get(), AbstractBlock.Properties.of(Material.DECORATION).instabreak().noOcclusion()));

    public static final RegistryObject<Block> MAPLE_PLANKS = register("maple_planks", () -> new Block(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.SNOW).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_MAPLE_LOG = register("stripped_maple_log", () -> new RotatedPillarBlock(AbstractBlock .Properties.of(Material.WOOD, MAPLE_PLANKS.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_MAPLE_WOOD = register("stripped_maple_wood", () -> new RotatedPillarBlock(AbstractBlock.Properties.of(Material.WOOD, MAPLE_PLANKS.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MAPLE_LOG = register("maple_log", () -> new ModLogBlock(STRIPPED_MAPLE_LOG.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, MaterialColor.SNOW).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MAPLE_WOOD = register("maple_wood", () -> new ModLogBlock(STRIPPED_MAPLE_WOOD.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, MAPLE_LOG.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MAPLE_STAIRS = register("maple_stairs", () -> new StairsBlock(() -> MAPLE_PLANKS.get().defaultBlockState(), AbstractBlock.Properties.copy(MAPLE_PLANKS.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MAPLE_SLAB = register("maple_slab", () -> new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, MAPLE_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MAPLE_FENCE = register("maple_fence", () -> new FenceBlock(AbstractBlock.Properties.of(Material.WOOD, MAPLE_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MAPLE_FENCE_GATE = register("maple_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.of(Material.WOOD, MAPLE_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MAPLE_DOOR = register("maple_door", () -> new DoorBlock(AbstractBlock.Properties.of(Material.WOOD, MAPLE_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MAPLE_TRAPDOOR = register("maple_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.of(Material.WOOD, MAPLE_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion().isValidSpawn(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MAPLE_PRESSURE_PLATE = register("maple_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.of(Material.WOOD, MAPLE_PLANKS.get().defaultMaterialColor()).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MAPLE_BUTTON = register("maple_button", () -> new WoodButtonBlock(AbstractBlock.Properties.of(Material.DECORATION).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MAPLE_LEAVES = register("maple_leaves", () -> new LeavesBlock(AbstractBlock.Properties.of(Material.LEAVES, MaterialColor.COLOR_RED).strength(0.2F).randomTicks().sound(SoundType.GRASS).noOcclusion().isValidSpawn(ModBlocks::ocelotOrParrot).isSuffocating(ModBlocks::never).isViewBlocking(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MAPLE_SAPLING = register("maple_sapling", () -> new SaplingBlock(new OakTree(),SaplingBlock.Properties.of(Material.PLANT).noCollission().randomTicks().instabreak().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MAPLE_SIGN = registerNoItem("maple_sign", () -> new StandingSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD), ModWoodType.MAPLE));
    public static final RegistryObject<Block> MAPLE_WALL_SIGN = registerNoItem("maple_wall_sign", () -> new WallSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(MAPLE_SIGN.get()), ModWoodType.MAPLE));
    public static final RegistryObject<Block> POTTED_MAPLE_SAPLING = registerNoItem("potted_maple_sapling", () -> new FlowerPotBlock(MAPLE_SAPLING.get(), AbstractBlock.Properties.of(Material.DECORATION).instabreak().noOcclusion()));

    public static final RegistryObject<Block> REDWOOD_PLANKS = register("redwood_planks", () -> new Block(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.SNOW).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_REDWOOD_LOG = register("stripped_redwood_log", () -> new RotatedPillarBlock(AbstractBlock .Properties.of(Material.WOOD, REDWOOD_PLANKS.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_REDWOOD_WOOD = register("stripped_redwood_wood", () -> new RotatedPillarBlock(AbstractBlock.Properties.of(Material.WOOD, REDWOOD_PLANKS.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> REDWOOD_LOG = register("redwood_log", () -> new ModLogBlock(STRIPPED_REDWOOD_LOG.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, MaterialColor.SNOW).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> REDWOOD_WOOD = register("redwood_wood", () -> new ModLogBlock(STRIPPED_REDWOOD_WOOD.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, REDWOOD_LOG.get().defaultMaterialColor()).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> REDWOOD_STAIRS = register("redwood_stairs", () -> new StairsBlock(() -> REDWOOD_PLANKS.get().defaultBlockState(), AbstractBlock.Properties.copy(REDWOOD_PLANKS.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> REDWOOD_SLAB = register("redwood_slab", () -> new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, REDWOOD_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> REDWOOD_FENCE = register("redwood_fence", () -> new FenceBlock(AbstractBlock.Properties.of(Material.WOOD, REDWOOD_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> REDWOOD_FENCE_GATE = register("redwood_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.of(Material.WOOD, REDWOOD_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> REDWOOD_DOOR = register("redwood_door", () -> new DoorBlock(AbstractBlock.Properties.of(Material.WOOD, REDWOOD_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> REDWOOD_TRAPDOOR = register("redwood_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.of(Material.WOOD, REDWOOD_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion().isValidSpawn(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> REDWOOD_PRESSURE_PLATE = register("redwood_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.of(Material.WOOD, REDWOOD_PLANKS.get().defaultMaterialColor()).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> REDWOOD_BUTTON = register("redwood_button", () -> new WoodButtonBlock(AbstractBlock.Properties.of(Material.DECORATION).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> REDWOOD_LEAVES = register("redwood_leaves", () -> new LeavesBlock(AbstractBlock.Properties.of(Material.LEAVES, MaterialColor.COLOR_RED).strength(0.2F).randomTicks().sound(SoundType.GRASS).noOcclusion().isValidSpawn(ModBlocks::ocelotOrParrot).isSuffocating(ModBlocks::never).isViewBlocking(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> REDWOOD_SAPLING = register("redwood_sapling", () -> new SaplingBlock(new OakTree(),SaplingBlock.Properties.of(Material.PLANT).noCollission().randomTicks().instabreak().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> REDWOOD_SIGN = registerNoItem("redwood_sign", () -> new StandingSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD), ModWoodType.REDWOOD));
    public static final RegistryObject<Block> REDWOOD_WALL_SIGN = registerNoItem("redwood_wall_sign", () -> new WallSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(REDWOOD_SIGN.get()), ModWoodType.REDWOOD));
    public static final RegistryObject<Block> POTTED_REDWOOD_SAPLING = registerNoItem("potted_redwood_sapling", () -> new FlowerPotBlock(REDWOOD_SAPLING.get(), AbstractBlock.Properties.of(Material.DECORATION).instabreak().noOcclusion()));

    public static final RegistryObject<Block> DEAD_PLANKS = register("dead_planks", () -> new Block(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_GRAY).strength(2, 3).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_DEAD_LOG = register("stripped_dead_log", () -> new RotatedPillarBlock(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_BLACK).strength(0.7f).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> STRIPPED_DEAD_WOOD = register("stripped_dead_wood", () -> new RotatedPillarBlock(AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_BLACK).strength(0.7f).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> DEAD_LOG = register("dead_log", () -> new ModLogBlock(STRIPPED_DEAD_LOG.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_GRAY).strength(0.7f).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> DEAD_WOOD = register("dead_wood", () -> new ModLogBlock(STRIPPED_DEAD_WOOD.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_GRAY).strength(0.7f).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> DEAD_STAIRS = register("dead_stairs", () -> new StairsBlock(() -> DEAD_PLANKS.get().defaultBlockState(), AbstractBlock.Properties.copy(DEAD_PLANKS.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> DEAD_SLAB = register("dead_slab", () -> new SlabBlock(AbstractBlock.Properties.of(Material.WOOD, DEAD_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> DEAD_FENCE = register("dead_fence", () -> new FenceBlock(AbstractBlock.Properties.of(Material.WOOD, DEAD_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> DEAD_FENCE_GATE = register("dead_fence_gate", () -> new FenceGateBlock(AbstractBlock.Properties.of(Material.WOOD, DEAD_PLANKS.get().defaultMaterialColor()).strength(2.0F, 3.0F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> DEAD_DOOR = register("dead_door", () -> new DoorBlock(AbstractBlock.Properties.of(Material.WOOD, DEAD_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion()), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> DEAD_TRAPDOOR = register("dead_trapdoor", () -> new TrapDoorBlock(AbstractBlock.Properties.of(Material.WOOD, DEAD_PLANKS.get().defaultMaterialColor()).strength(3.0F).sound(SoundType.WOOD).noOcclusion().isValidSpawn(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> DEAD_PRESSURE_PLATE = register("dead_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.of(Material.WOOD, DEAD_PLANKS.get().defaultMaterialColor()).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> DEAD_BUTTON = register("dead_button", () -> new WoodButtonBlock(AbstractBlock.Properties.of(Material.DECORATION).noCollission().strength(0.5F).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> DEAD_LEAVES = register("dead_leaves", () -> new LeavesBlock(AbstractBlock.Properties.of(Material.LEAVES, MaterialColor.COLOR_BROWN).strength(0.2F).randomTicks().sound(SoundType.GRASS).noOcclusion().isValidSpawn(ModBlocks::ocelotOrParrot).isSuffocating(ModBlocks::never).isViewBlocking(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> DEAD_SIGN = registerNoItem("dead_sign", () -> new StandingSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD), ModWoodType.DEAD));
    public static final RegistryObject<Block> DEAD_WALL_SIGN = registerNoItem("dead_wall_sign", () -> new WallSignBlock(AbstractBlock.Properties.of(Material.WOOD).noCollission().strength(1.0F).sound(SoundType.WOOD).dropsLike(DEAD_SIGN.get()), ModWoodType.REDWOOD));
    public static final RegistryObject<Block> CHARRED_LOG = register("charred_log", () -> new CharredLogBlock(STRIPPED_DEAD_LOG.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_BLACK).strength(0.7f).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CHARRED_WOOD = register("charred_wood", () -> new CharredLogBlock(STRIPPED_DEAD_WOOD.get().defaultBlockState(), AbstractBlock.Properties.of(Material.WOOD, MaterialColor.COLOR_BLACK).strength(0.7f).harvestLevel(0).harvestTool(ToolType.AXE).sound(SoundType.WOOD)), ModItemGroup.TAB_ARCHAICRAFT);

    public static final RegistryObject<Block> MUD = register("mud", () -> new MudBlock(AbstractBlock.Properties.of(Material.CLAY, MaterialColor.COLOR_BROWN).speedFactor(0.6F).strength(0.2F).sound(SoundType.WET_GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MUD_BRICKS = register("mud_bricks", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.DIRT).requiresCorrectToolForDrops().strength(1.8F, 5.0F)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MUD_BRICK_STAIRS = register("mud_brick_stairs", () -> new StairsBlock(MUD_BRICKS.get().defaultBlockState(), AbstractBlock.Properties.copy(MUD_BRICKS.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MUD_BRICK_SLAB = register("mud_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.copy(MUD_BRICKS.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MUD_BRICK_WALL = register("mud_brick_wall", () -> new WallBlock(AbstractBlock.Properties.copy(MUD_BRICKS.get())), ModItemGroup.TAB_ARCHAICRAFT);

    public static final RegistryObject<Block> ADOBE = register("adobe", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.WOOD).requiresCorrectToolForDrops().strength(1.8F, 5.0F)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> PAINTED_ADOBE = register("painted_adobe", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.SNOW).requiresCorrectToolForDrops().strength(1.8F, 5.0F)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ADOBE_STAIRS = register("adobe_stairs", () -> new StairsBlock(ADOBE.get().defaultBlockState(), AbstractBlock.Properties.copy(ADOBE.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ADOBE_SLAB = register("adobe_slab", () -> new SlabBlock(AbstractBlock.Properties.copy(ADOBE.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ADOBE_WALL = register("adobe_wall", () -> new WallBlock(AbstractBlock.Properties.copy(ADOBE.get())), ModItemGroup.TAB_ARCHAICRAFT);

    public static final RegistryObject<Block> ASH = register("ash", () -> new Block(AbstractBlock.Properties.of(Material.SAND, MaterialColor.COLOR_LIGHT_GRAY).strength(0.5F).sound(SoundType.SNOW)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASH_BRICKS = register("ash_bricks", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.DIRT).requiresCorrectToolForDrops().strength(1.8F, 5.0F)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASH_BRICK_STAIRS = register("ash_brick_stairs", () -> new StairsBlock(ASH_BRICKS.get().defaultBlockState(), AbstractBlock.Properties.copy(ASH_BRICKS.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASH_BRICK_SLAB = register("ash_brick_slab", () -> new SlabBlock(AbstractBlock.Properties.copy(ASH_BRICKS.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ASH_BRICK_WALL = register("ash_brick_wall", () -> new WallBlock(AbstractBlock.Properties.copy(ASH_BRICKS.get())), ModItemGroup.TAB_ARCHAICRAFT);

    public static final RegistryObject<Block> WHITE_SAND = register("white_sand", () -> new SandBlock(11098145, AbstractBlock.Properties.of(Material.SAND, MaterialColor.SNOW).strength(0.5F).sound(SoundType.SAND)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> WHITE_SANDSTONE = register("white_sandstone", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.SNOW).requiresCorrectToolForDrops().strength(0.8F)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CHISELED_WHITE_SANDSTONE = register("chiseled_white_sandstone", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.SNOW).requiresCorrectToolForDrops().strength(0.8F)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CUT_WHITE_SANDSTONE = register("cut_white_sandstone", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.SNOW).requiresCorrectToolForDrops().strength(0.8F)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> WHITE_SANDSTONE_STAIRS = register("white_sandstone_stairs", () -> new StairsBlock(WHITE_SANDSTONE.get().defaultBlockState(), AbstractBlock.Properties.copy(WHITE_SANDSTONE.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> WHITE_SANDSTONE_SLAB = register("white_sandstone_slab", () -> new SlabBlock(AbstractBlock.Properties.of(Material.STONE, MaterialColor.SNOW).requiresCorrectToolForDrops().strength(2.0F, 6.0F)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CUT_WHITE_SANDSTONE_SLAB = register("cut_white_sandstone_slab", () -> new SlabBlock(AbstractBlock.Properties.of(Material.STONE, MaterialColor.SNOW).requiresCorrectToolForDrops().strength(2.0F, 6.0F)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> SMOOTH_WHITE_SANDSTONE = register("smooth_white_sandstone", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.SNOW).requiresCorrectToolForDrops().strength(2.0F, 6.0F)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> SMOOTH_WHITE_SANDSTONE_STAIRS = register("smooth_white_sandstone_stairs", () -> new StairsBlock(SMOOTH_WHITE_SANDSTONE.get().defaultBlockState(), AbstractBlock.Properties.copy(SMOOTH_WHITE_SANDSTONE.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> SMOOTH_WHITE_SANDSTONE_SLAB = register("smooth_white_sandstone_slab", () -> new SlabBlock(AbstractBlock.Properties.copy(SMOOTH_WHITE_SANDSTONE.get())), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> WHITE_SANDSTONE_WALL = register("white_sandstone_wall", () -> new WallBlock(AbstractBlock.Properties.copy(WHITE_SANDSTONE.get())), ModItemGroup.TAB_ARCHAICRAFT);

    public static final RegistryObject<Block> DRIED_GRASS_BLOCK = register("dried_grass_block", () -> new SnowyDirtBlock(AbstractBlock.Properties.of(Material.GRASS, MaterialColor.COLOR_BROWN).randomTicks().strength(0.6F).sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> DRIED_GRASS = register("dried_grass", () -> new DriedTallGrassBlock(AbstractBlock.Properties.of(Material.REPLACEABLE_PLANT).noCollission().instabreak().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CHARRED_GRASS_BLOCK = register("charred_grass_block", () -> new SnowyDirtBlock(AbstractBlock.Properties.of(Material.GRASS, MaterialColor.COLOR_BROWN).randomTicks().strength(0.6F).sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CHARRED_GRASS = register("charred_grass", () -> new DriedTallGrassBlock(AbstractBlock.Properties.of(Material.REPLACEABLE_PLANT).noCollission().instabreak().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> LITTERFALL = register("litterfall", () -> new SnowyDirtBlock(AbstractBlock.Properties.of(Material.GRASS, MaterialColor.COLOR_PURPLE).randomTicks().strength(0.6F).sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CLOVER_BLOCK = register("clover_block", () -> new SnowyDirtBlock(AbstractBlock.Properties.of(Material.GRASS).randomTicks().strength(0.6F).sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CLOVER = register("clover", () -> new TallGrassBlock(AbstractBlock.Properties.of(Material.REPLACEABLE_PLANT).noCollission().instabreak().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> LOTUS_FLOWER = registerNoItem("lotus_flower", () -> new LotusFlowerBlock(AbstractBlock.Properties.of(Material.PLANT).instabreak().sound(SoundType.LILY_PAD).noOcclusion()));
    public static final RegistryObject<Block> CATTAIL = register("cattail", () -> new CattailBlock(AbstractBlock.Properties.of(Material.PLANT, MaterialColor.TERRACOTTA_LIGHT_GREEN).noCollission().instabreak().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> WOLFSBANE = register("wolfsbane", () -> new FlowerBlock(Effects.POISON, 23, AbstractBlock.Properties.of(Material.PLANT, MaterialColor.COLOR_PURPLE).noCollission().instabreak().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);

    public static final RegistryObject<Block> WIZARDS_SPIRE = register("wizards_spire", () -> new AzurecapBlock(AbstractBlock.Properties.of(Material.PLANT, MaterialColor.COLOR_CYAN).instabreak().noCollission().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> AZURECAP = register("azurecap", () -> new AzurecapBlock(AbstractBlock.Properties.of(Material.PLANT, MaterialColor.COLOR_CYAN).instabreak().noCollission().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> BITTERSWEET = register("bittersweet", () -> new BittersweetBlock(AbstractBlock.Properties.of(Material.PLANT, MaterialColor.COLOR_RED).instabreak().noCollission().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CHALKGILL = register("chalkgill", () -> new ChalkgillBlock(AbstractBlock.Properties.of(Material.PLANT, MaterialColor.TERRACOTTA_WHITE).instabreak().noCollission().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MIDNIGHT_GOBLET = register("midnight_goblet", () -> new MidnightGobletBlock(AbstractBlock.Properties.of(Material.PLANT, MaterialColor.TERRACOTTA_BLACK).instabreak().noCollission().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> OCRE_AGARIC = register("ocre_agaric", () -> new OcreAgaricBlock(AbstractBlock.Properties.of(Material.PLANT, MaterialColor.COLOR_BROWN).instabreak().noCollission().sound(SoundType.GRASS)), ModItemGroup.TAB_ARCHAICRAFT);

    public static final RegistryObject<Block> MOONSTONE_ORE = register("moonstone_ore", () -> new OreBlock(AbstractBlock.Properties.of(Material.STONE).requiresCorrectToolForDrops().strength(3.0F, 3.0F)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> MOONSTONE_BLOCK = register("moonstone_block", () -> new Block(AbstractBlock.Properties.of(Material.METAL, MaterialColor.TERRACOTTA_LIGHT_BLUE).requiresCorrectToolForDrops().strength(5.0F, 6.0F).sound(SoundType.METAL)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CINNABAR_ORE = register("cinnabar_ore", () -> new OreBlock(AbstractBlock.Properties.of(Material.STONE).requiresCorrectToolForDrops().strength(3.0F, 3.0F)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> CINNABAR_BLOCK = register("cinnabar_block", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.TERRACOTTA_RED).requiresCorrectToolForDrops().strength(5.0F, 6.0F).sound(SoundType.METAL).isRedstoneConductor(ModBlocks::never)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> SULPHUR_ORE = register("sulphur_ore", () -> new OreBlock(AbstractBlock.Properties.of(Material.STONE).requiresCorrectToolForDrops().strength(3.0F, 3.0F)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> SULPHUR_BLOCK = register("sulphur_block", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.TERRACOTTA_YELLOW).requiresCorrectToolForDrops().strength(3.0F, 3.0F)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ARCTICITE_ORE = register("arcticite_ore", () -> new ArcticiteOreBlock(AbstractBlock.Properties.of(Material.STONE, MaterialColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(1.25F, 4.2F).randomTicks().lightLevel(litBlockEmission(9)).sound(SoundType.BASALT)), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> ARCTICITE_BLOCK = register("arcticite_block", () -> new Block(AbstractBlock.Properties.of(Material.METAL, MaterialColor.LAPIS).requiresCorrectToolForDrops().strength(3.0F, 3.0F)), ModItemGroup.TAB_ARCHAICRAFT);

    public static final RegistryObject<Block> MORTAR = register("mortar", () -> new MortarBlock(AbstractBlock.Properties.of(Material.STONE).sound(SoundType.STONE).strength(3.5f, 3.5f).harvestLevel(1).harvestTool(ToolType.PICKAXE).requiresCorrectToolForDrops()), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> KILN = register("kiln", () -> new KilnBlock(AbstractBlock.Properties.of(Material.STONE).sound(SoundType.STONE).strength(3.5f, 3.5f).harvestLevel(1).harvestTool(ToolType.PICKAXE).requiresCorrectToolForDrops()), ModItemGroup.TAB_ARCHAICRAFT);
    public static final RegistryObject<Block> TABLE = register("table", () -> new TableBlock(AbstractBlock.Properties.of(Material.WOOD).sound(SoundType.WOOD).strength(2f, 3f).harvestLevel(1).harvestTool(ToolType.AXE).requiresCorrectToolForDrops()), ModItemGroup.TAB_ARCHAICRAFT);

    private static ToIntFunction<BlockState> litBlockEmission(int p_235420_0_) {
        return (p_235421_1_) -> {
            return p_235421_1_.getValue(BlockStateProperties.LIT) ? p_235420_0_ : 0;
        };
    }
    private static Boolean never(BlockState p_235427_0_, IBlockReader p_235427_1_, BlockPos p_235427_2_, EntityType<?> p_235427_3_) {
        return (boolean)false;
    }
    private static Boolean always(BlockState p_235437_0_, IBlockReader p_235437_1_, BlockPos p_235437_2_, EntityType<?> p_235437_3_) {
        return (boolean)true;
    }

    private static Boolean ocelotOrParrot(BlockState p_235441_0_, IBlockReader p_235441_1_, BlockPos p_235441_2_, EntityType<?> p_235441_3_) {
        return p_235441_3_ == EntityType.OCELOT || p_235441_3_ == EntityType.PARROT;
    }
    private static boolean never(BlockState p_235436_0_, IBlockReader p_235436_1_, BlockPos p_235436_2_) {
        return false;
    }

    static void register() {}
    private static <T extends Block> RegistryObject<T> registerNoItem(String name, Supplier<T> block) {
        return Registration.BLOCKS.register(name, block);
    }
    private static <T extends Block> RegistryObject<T> register(String name, Supplier<T> block, ItemGroup group) {
        RegistryObject<T> ret = registerNoItem(name, block);
        Registration.ITEMS.register(name, () -> new BlockItem(ret.get(), new Item.Properties().tab(group)));
        return ret;
    }
}